### ISSUE TITLE
[BUG] Module interfering with some functions of Better Rolls 2

### ISSUE THREAD

**Issue by sroakjp** [mrcomac/swade-animated#2]
*[Please be aware if you are not able to fill the items below I won't be able to help. Also those text below, including this one, are descriptions for each section, please remove accordingly]*

**Item**
- Type: [ weapon ]
- Name: [ Bastard sword ]

**Describe the bug**
Using the Better Rolls 2 module, which automatically applies vulnerable when a token makes a wild attack. The vulnerable status is no longer being applied after activating the swade-animated module. Expected behavior resumed after deactivating this module.

**To Reproduce**
1. Select a token with a weapon
2. Target another token
3. Select the weapon to send the BR2 action card to the chat window.
4. Toggle on Wild Attack
5. Click Roll - Vulnerable status should be applied at this point
6. See error

**Expected behavior**
SWADE-animated does not interfere in the behavior of the Better Rolls 2 module.

**Logs**
Please, follow the following steps to reproduce the error and send to us the console log.
1. Enable Debug Mode from module's configure
1 Open your console in your browser
2. Prepare the scene, open all you need.
3. Clear your console output
4. Reproduce the error
7. Copy the output and past the output in this section. - output in attached text file

**Environment details (please complete the following information):**
 - FoundryVTT version [Version 11 build 305]: 
 - Browser [chrome]:
 - Module Version [0.0.1]:
- Modules enabled: [See images below]

![image](https://github.com/mrcomac/swade-animated/assets/62338951/278b3bdb-7249-481d-9047-c58fc71e650d)
![image](https://github.com/mrcomac/swade-animated/assets/62338951/75c6d773-c8c0-465c-a5d5-d4cc9e7f1b80)

**Additional context**
[Issue Console Log.txt](https://github.com/mrcomac/swade-animated/files/12045542/Issue.Console.Log.txt)

**Comment by mrcomac** [comment]
It's working for me.

It might be a issue with the item. Can you please export your weapon item and attach to this thread?

![output](https://github.com/mrcomac/swade-animated/assets/6748594/6ce6dc4d-2639-4117-9869-ded40cbfa4e6)

**Comment by sroakjp** [comment]
So it appears we are both using Token Action HUD. BR2 appears to be working for me if I open the item card directly from the sheet, but not when I select it from the HUD. So the issue appears to be something broken in the interaction between my HUD and this module. But that is strange since you are not having that issue.

**Comment by sroakjp** [comment]
How can I export an item to attach to this thread?

**Comment by sroakjp** [comment]
After disabling the animation module I'm still having the issue. I'm not sure why disabling it before fixed it, except I may have accidentally disabled the HUD as well and did my testing without it. So I think the real issue is between the HUD and BR2. I think you can close this issue given that new data.

**Comment by mrcomac** [comment]
I recommend you disable all modules and enable one by one to test this issue.
