### ISSUE TITLE
Unable to activate the module on latest version of foundry

### ISSUE THREAD

**Issue by sroakjp** [mrcomac/swade-animated#5]
**Describe the bug**
Unable to activate the module on latest version of foundry. Module does not even appear in list of modules within Foundry.

**To Reproduce**

**Expected behavior**
Should be able to activate the module if the module is compatible with the same core version I'm using, even if not validated, unless there is a known incompatibilty.

**Environment details (please complete the following information):**
 - FoundryVTT version: version 11 build 308: 
 - Browser: Chrome
 - Module Version [e.g. 1.0.0]: 0.0.4
- Modules enabled: Many, N/A for this issue

**Additional context**
![image](https://github.com/mrcomac/swade-animated/assets/62338951/9467e914-803e-4fde-a9f2-ee92d3237396)

Full message says:
Metadata validation failed for module "swade-animated": The file "scripts/init.js" included by module swade-animated does not exist

**Comment by mrcomac** [comment]
Sorry the deelay on this.
it should be fixed in the new release 0.0.5. Also i've added more animations related to Deadlands.
